### ISSUE TITLE
ゲーム設定画面のUIサイズと視認性を改善する

### ISSUE THREAD

**Issue by systemcmd0122** [systemcmd0122/tetris#1]
## 現在の問題
- 設定画面のボードが小さく、見にくい状態になっている
- ボード内のコンテンツが縮小されており、視認性が悪い

## 改善提案
以下の修正を行い、設定画面のUIを改善する必要があります：

1. ボードのサイズ調整
- より広い画面スペースを活用できるよう、ボードサイズを拡大
- レスポンシブ対応を確保しつつ、最適な表示サイズを設定

2. コンテンツの表示改善
- テキストやコントロール要素のサイズを適切に調整
- 要素間の余白を十分に確保
- フォントサイズの最適化

3. レイアウトの最適化
- コンテンツの配置を整理し、見やすく再構成
- 重要な設定項目が目立つようにデザインを調整

## 技術的な実装案
```css
.settings-board {
  min-width: 80%;
  max-width: 1200px;
  margin: 2rem auto;
  padding: 2rem;
}

.settings-content {
  font-size: 1rem;
  line-height: 1.5;
}

.settings-controls {
  margin: 1rem 0;
  gap: 1rem;
}
```

## 期待される結果
- 設定画面が見やすく、使いやすくなる
- ユーザーが設定を容易に確認・変更できる
- 画面サイズに関わらず適切に表示される
